name: Deploy Qt Tic-Tac-Toe to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
      ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
      ECS_TASK_DEFINITION: .aws/task-definition.json
      CONTAINER_NAME: tic-tac-toe-game

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug Variables Before AWS Authentication
      run: |
        echo "=== Pre-Authentication Debug ==="
        echo "AWS_REGION: ${{ env.AWS_REGION }}"
        echo "ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY != '' && vars.ECR_REPOSITORY || 'NOT SET' }}"
        echo "ECS_SERVICE: ${{ vars.ECS_SERVICE != '' && vars.ECS_SERVICE || 'NOT SET' }}"
        echo "ECS_CLUSTER: ${{ vars.ECS_CLUSTER != '' && vars.ECS_CLUSTER || 'NOT SET' }}"
        echo "Secrets configured: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' && 'YES' || 'NO' }}"
        echo "==============================="

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Discover ECR Repositories
      run: |
        echo "=== Available ECR Repositories ==="
        aws ecr describe-repositories --region ${{ env.AWS_REGION }} --query 'repositories[].repositoryName' --output table || echo "Failed to list repositories"
        echo "================================="

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Continue with rest of your workflow...
