name: Multi-Platform Qt Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt-version: ['6.5.0']
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        
    - name: Build on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        qmake
        make
        
    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        qmake
        nmake
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-app-${{ matrix.os }}
        path: ./build/
